version: '3'

services:
  workspace:
    image: web-node:latest
    build:
      context: ./workspace
    container_name: web-node
    working_dir: /tinny-docker/web/
    tty: true

  nginx:
    image: web-nginx:latest
    build:
      context: ./nginx
    container_name: web-nginx-adonis
    working_dir: /tinny-docker/web/
    depends_on:
      - workspace
    ports:
    - 80:80
    - 443:443

  mysql:
    image: web-mysql:latest
    build:
      context: ./mysql
    container_name: web-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

    phpmyadmin:
      image: web-mysql-admin:lastest
      build:
        context: ./phpmyadmin
      container_name: web-mysql-admin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1