version: '3'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  workspace-node:
    image: tinny-node
    build:
      context: ./workspace-node
    container_name: tinny-node
    working_dir: /web
    volumes:
    - ../web:/web
    tty: true
    networks:
      - frontend
      - backend

  workspace-php:
    image: tinny-php
    build:
      context: ./workspace-php
    container_name: tinny-php
    working_dir: /web
    volumes:
      - ../web:/web
    tty: true
    networks:
      - frontend
      - backend

  nginx:
    image: tinny-nginx
    build:
      context: ./nginx
    container_name: tinny-nginx
    working_dir: /web
    volumes_from:
      - workspace-php
    ports:
    - 80:80
    - 443:443
    networks:
      - frontend

  mysql:
    image: tinny-mysql
    build:
      context: ./mysql
    container_name: tinny-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
    - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: tinny-mysql-admin
    build:
      context: ./phpmyadmin
    container_name: tinny-mysql-admin
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=web-mysql
      - PMA_ABSOLUTE_URI=http://admin.tiny-docker.local/
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - frontend
      - backend
